import { randomUUID } from "node:crypto";
import type { Pool, RowDataPacket } from "mysql2/promise";

export type RecognitionTaskKind = "single_question" | "homework_page";
export type RecognitionTaskStatus = "pending" | "processing" | "succeeded" | "failed";
export type RecognitionTask = { id: string; parentAccountId: string; childProfileId: string; draftId: string | null; kind: RecognitionTaskKind; imageKey: string; imageUrl: string | null; status: RecognitionTaskStatus; attempts: number; result: unknown | null; errorCode: string | null; idempotencyKey: string; createdAt: number; updatedAt: number; expiresAt: number };
export interface RecognitionTaskStore { create(input: Omit<RecognitionTask, "id" | "status" | "attempts" | "result" | "errorCode" | "createdAt" | "updatedAt">): Promise<RecognitionTask>; find(parentAccountId: string, id: string): Promise<RecognitionTask | undefined>; claim(id: string): Promise<RecognitionTask | undefined>; complete(id: string, result: unknown): Promise<void>; fail(id: string, errorCode: string): Promise<void>; }
export class InMemoryRecognitionTaskStore implements RecognitionTaskStore {
  private readonly tasks = new Map<string, RecognitionTask>();
  async create(input: Omit<RecognitionTask, "id" | "status" | "attempts" | "result" | "errorCode" | "createdAt" | "updatedAt">): Promise<RecognitionTask> { const existing = [...this.tasks.values()].find((v) => v.parentAccountId === input.parentAccountId && v.idempotencyKey === input.idempotencyKey && v.status !== "failed"); if (existing) return existing; const now = Date.now(); const task: RecognitionTask = { ...input, id: randomUUID(), status: "pending", attempts: 0, result: null, errorCode: null, createdAt: now, updatedAt: now }; this.tasks.set(task.id, task); return task; }
  async find(parentAccountId: string, id: string) { const task = this.tasks.get(id); return task?.parentAccountId === parentAccountId ? task : undefined; }
  async claim(id: string) { const task = this.tasks.get(id); if (!task || task.status !== "pending") return undefined; task.status = "processing"; task.attempts += 1; task.updatedAt = Date.now(); return task; }
  async complete(id: string, result: unknown) { const task = this.tasks.get(id); if (!task) return; task.status = "succeeded"; task.result = result; task.updatedAt = Date.now(); }
  async fail(id: string, errorCode: string) { const task = this.tasks.get(id); if (!task) return; task.status = "failed"; task.errorCode = errorCode; task.updatedAt = Date.now(); }
}
export class MysqlRecognitionTaskStore implements RecognitionTaskStore {
  constructor(private readonly pool: Pool) {}
  async create(input: Omit<RecognitionTask, "id" | "status" | "attempts" | "result" | "errorCode" | "createdAt" | "updatedAt">) { const [found] = await this.pool.query<RowDataPacket[]>("SELECT * FROM recognition_tasks WHERE parent_account_id=? AND idempotency_key=? AND status!='failed' LIMIT 1", [input.parentAccountId, input.idempotencyKey]); if (found[0]) return row(found[0]); const now = Date.now(); const task: RecognitionTask = { ...input, id: randomUUID(), status: "pending", attempts: 0, result: null, errorCode: null, createdAt: now, updatedAt: now }; await this.pool.execute("INSERT INTO recognition_tasks (id,parent_account_id,child_profile_id,draft_id,kind,image_key,image_url,status,attempts,idempotency_key,created_at,updated_at,expires_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?)", [task.id,task.parentAccountId,task.childProfileId,task.draftId,task.kind,task.imageKey,task.imageUrl,task.status,0,task.idempotencyKey,now,now,task.expiresAt]); return task; }
  async find(parentAccountId: string, id: string) { const [rows] = await this.pool.query<RowDataPacket[]>("SELECT * FROM recognition_tasks WHERE id=? AND parent_account_id=?", [id,parentAccountId]); return rows[0] ? row(rows[0]) : undefined; }
  async claim(id: string) { const [result] = await this.pool.execute("UPDATE recognition_tasks SET status='processing',attempts=attempts+1,updated_at=? WHERE id=? AND status='pending'", [Date.now(),id]); if ((result as any).affectedRows !== 1) return undefined; const [rows] = await this.pool.query<RowDataPacket[]>("SELECT * FROM recognition_tasks WHERE id=?",[id]); return rows[0] ? row(rows[0]) : undefined; }
  async complete(id: string, result: unknown) { await this.pool.execute("UPDATE recognition_tasks SET status='succeeded',result_json=?,updated_at=? WHERE id=?", [JSON.stringify(result),Date.now(),id]); }
  async fail(id: string, errorCode: string) { await this.pool.execute("UPDATE recognition_tasks SET status='failed',error_code=?,updated_at=? WHERE id=?", [errorCode,Date.now(),id]); }
}
function row(v: RowDataPacket): RecognitionTask { return { id:String(v.id),parentAccountId:String(v.parent_account_id),childProfileId:String(v.child_profile_id),draftId:v.draft_id as string|null,kind:v.kind as RecognitionTaskKind,imageKey:String(v.image_key),imageUrl:v.image_url as string|null,status:v.status as RecognitionTaskStatus,attempts:Number(v.attempts),result:v.result_json ? JSON.parse(String(v.result_json)) : null,errorCode:v.error_code as string|null,idempotencyKey:String(v.idempotency_key),createdAt:Number(v.created_at),updatedAt:Number(v.updated_at),expiresAt:Number(v.expires_at) }; }
