#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

PACKAGE_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
MINIPROGRAM_DIR="$PACKAGE_ROOT/miniprogram"
ENV_FILE="$PACKAGE_ROOT/.env"
PORT="${PORT:-3000}"

TOTAL_STAGES=6

banner "微信开发者工具 · 真实测试向导"

# ── Stage 1: 环境与 DeepSeek Key ──────────────────────────────────────────
stage "环境检查与 DeepSeek Key"
if ! command -v node >/dev/null 2>&1; then
  warn "未找到 node。请先安装 Node.js 20+：https://nodejs.org"
  exit 1
fi
NODE_MAJOR=$(node -e 'console.log(process.versions.node.split(".")[0])')
if [[ "$NODE_MAJOR" -lt 20 ]]; then
  warn "node 版本 $(node -v) 过低，需要 20+。"
  exit 1
fi
say "node $(node -v) ✓"

cd "$PACKAGE_ROOT"
if [[ ! -d node_modules ]]; then
  step "安装依赖（npm install）…"
  npm install
fi
say "依赖已就绪 ✓"

if [[ -n "${DEEPSEEK_API_KEY:-}" ]]; then
  say "检测到环境中的 DEEPSEEK_API_KEY，写入 $ENV_FILE 供服务使用。"
  write_env DEEPSEEK_API_KEY "$DEEPSEEK_API_KEY"
else
  say "讲解与题目识别需要 DeepSeek API Key（platform.deepseek.com → API keys）。"
  note "没有 key 也可以继续：服务照常启动，只是识别/讲解接口会报错。"
  if confirm "现在提供 DEEPSEEK_API_KEY 吗？"; then
    ask_secret DEEPSEEK_API_KEY "粘贴 DeepSeek API Key（sk-…）:"
    write_env DEEPSEEK_API_KEY "$DEEPSEEK_API_KEY"
  else
    SKIPPED+=("DEEPSEEK_API_KEY（识别与讲解将不可用）")
  fi
fi

# ── Stage 2: 启动本地服务并冒烟测试 ────────────────────────────────────────
stage "启动本地服务并冒烟测试"
SMOKE=$(curl -s -m 2 -X POST "http://127.0.0.1:$PORT/api/session" \
  -H 'content-type: application/json' -d '{"code":"wizard-smoke"}' || true)
if [[ "$SMOKE" == *'"token"'* ]]; then
  say "服务已在 $PORT 端口运行 ✓（复用现有进程）"
else
  step "后台启动服务（日志：/tmp/mistake-notebook-server.log）…"
  (
    cd "$PACKAGE_ROOT"
    set -a; [[ -f "$ENV_FILE" ]] && source "$ENV_FILE"; set +a
    nohup npx tsx src/server/start.ts >/tmp/mistake-notebook-server.log 2>&1 &
    echo $! > /tmp/mistake-notebook-server.pid
  )
  for _ in 1 2 3 4 5 6 7 8 9 10; do
    sleep 1
    SMOKE=$(curl -s -m 2 -X POST "http://127.0.0.1:$PORT/api/session" \
      -H 'content-type: application/json' -d '{"code":"wizard-smoke"}' || true)
    [[ "$SMOKE" == *'"token"'* ]] && break
  done
  if [[ "$SMOKE" == *'"token"'* ]]; then
    say "服务已启动并通过冒烟测试 ✓（PID 见 /tmp/mistake-notebook-server.pid）"
  else
    warn "服务未能响应。查看日志：tail /tmp/mistake-notebook-server.log"
    exit 1
  fi
fi
note "停止服务：kill \$(cat /tmp/mistake-notebook-server.pid)"
pause "服务正常。按 Enter 继续"

# ── Stage 3: 局域网地址写入小程序配置 ──────────────────────────────────────
stage "真机访问地址（局域网 IP）"
say "真机通过局域网访问你电脑上的服务，需要电脑的局域网 IP。"
DETECTED_IP=$(ipconfig getifaddr en0 2>/dev/null || hostname -I 2>/dev/null | awk '{print $1}' || true)
say "检测到：${DETECTED_IP:-未检测到}"
LAN_IP="$DETECTED_IP"
if ! confirm "使用 ${DETECTED_IP:-这个地址} 吗？"; then
  say "请手动输入（系统设置 → Wi-Fi → 详细信息里可查看）："
  ask LAN_IP "局域网 IP（如 192.168.1.8）:"
fi
if [[ -z "$LAN_IP" ]]; then
  warn "未设置 IP，跳过。之后手动修改 miniprogram/config.js 的 apiBase。"
  SKIPPED+=("局域网 IP 写入 miniprogram/config.js")
else
  cat > "$MINIPROGRAM_DIR/config.js" <<EOF
module.exports = {
  // 开发环境指向本机 npm start 启动的服务；上线前替换为正式域名。
  apiBase: "http://$LAN_IP:$PORT/api",
};
EOF
  say "已写入 miniprogram/config.js → http://$LAN_IP:$PORT/api ✓"
fi
warn "手机与电脑必须连接同一个 Wi-Fi。"
pause "按 Enter 继续"

# ── Stage 4: 安装并导入微信开发者工具 ─────────────────────────────────────
stage "安装并导入微信开发者工具"
if [[ -d "/Applications/wechatwebdevtools.app" ]]; then
  say "已安装微信开发者工具 ✓"
else
  step "下载并安装「微信开发者工具」Stable 版（macOS）。"
  open_url "https://developers.weixin.qq.com/miniprogram/dev/devtools/download.html"
  pause "安装完成后按 Enter 继续"
fi
say "导入项目："
step "打开微信开发者工具 → 左侧「小程序」→「+」导入项目"
step "目录选择：$MINIPROGRAM_DIR"
step "AppID：选「测试号」即可完整体验；若已注册小程序，填真实 AppID"
if confirm "你有已注册的小程序 AppID 吗？（没有就选测试号，回 N）"; then
  ask APPID "粘贴 AppID（wx…）:"
  if [[ -n "$APPID" ]]; then
    sed -i '' "s/\"appid\": \"[^\"]*\"/\"appid\": \"$APPID\"/" \
      "$MINIPROGRAM_DIR/project.config.json"
    say "已写入 project.config.json ✓"
  fi
fi
pause "项目已在开发者工具中打开后，按 Enter 继续"

# ── Stage 5: 关闭域名校验并编译 ───────────────────────────────────────────
stage "关闭域名校验并编译"
say "本地/局域网调试地址不是 HTTPS，需要关闭域名校验："
step "开发者工具右上角「详情」→「本地设置」"
step "勾选「不校验合法域名、web-view（业务域名）、TLS 版本以及 HTTPS 证书」"
step "点击「编译」，模拟器中应出现首页（首次为「监护人确认」页）"
if ! confirm "模拟器里首页加载成功了吗？"; then
  warn "若请求失败：确认 Stage 2 的服务仍在运行，且 config.js 地址正确。"
  note "控制台报错可贴给 Codex 继续排查。"
  exit 1
fi

# ── Stage 6: 真机预览与验收 ───────────────────────────────────────────────
stage "真机预览与验收"
say "把小程序跑到真实手机上："
step "开发者工具工具栏点「预览」，用手机微信扫码"
step "手机上打开后：右上角「···」→「打开调试」（开发调试模式才会放行局域网地址）"
say ""
say "验收清单（按顺序走一遍）："
step "监护人确认 → 创建孩子档案（昵称/年级/地区）"
step "首页点「拍一道题」→ 拍照 → 上传并识别 → 核对题干后确认"
step "讲解页逐级展开：先想一想 → 思路 → 分步 → 答案（默认需家长在「我的」里开启）"
step "填写主知识点，保存到错题本"
step "首页出现待办与七日摘要；「错题本」可筛选；「周报」如实显示"
note "复习默认明天到期；想立即体验可在「我的」里用调试入口升级订阅后再回到首页。"
say ""
if confirm "全流程走通了吗？"; then
  say "真机验收通过 🎉"
else
  warn "把卡住的一步（页面/报错/截图）反馈给 Codex 继续修。"
fi
# ──────────────────────────────────────────────────────────────────────────

finish
